In [76]:
import pandas as pd

In [77]:
dataset = pd.read_csv("Churn_Modelling.csv")
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [78]:
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [79]:
X
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [80]:
from sklearn.preprocessing import LabelEncoder

In [81]:
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [82]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [83]:
ct  = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[1])], remainder='passthrough')
X = ct.fit_transform(X)

In [84]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [85]:
from sklearn.model_selection import train_test_split

In [86]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [87]:
from sklearn.preprocessing import StandardScaler

In [88]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [89]:
import tensorflow as tf

In [90]:
ann = tf.keras.models.Sequential()

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [91]:
ann.compile(optimizer='adam', metrics=['accuracy'], loss='binary_crossentropy')

In [92]:
ann.fit(X_train, y_train, batch_size=50, epochs=100)

Epoch 1/100
160/160 [==============================] - 2s 2ms/step - loss: 0.5694 - accuracy: 0.7821
Epoch 2/100
160/160 [==============================] - 0s 2ms/step - loss: 0.4786 - accuracy: 0.7928
Epoch 3/100
160/160 [==============================] - 0s 2ms/step - loss: 0.4491 - accuracy: 0.7976
Epoch 4/100
160/160 [==============================] - 0s 2ms/step - loss: 0.4467 - accuracy: 0.7889
Epoch 5/100
160/160 [==============================] - 0s 2ms/step - loss: 0.4391 - accuracy: 0.7904
Epoch 6/100
160/160 [==============================] - 0s 2ms/step - loss: 0.4317 - accuracy: 0.7958
Epoch 7/100
160/160 [==============================] - 0s 2ms/step - loss: 0.4320 - accuracy: 0.8166
Epoch 8/100
160/160 [==============================] - 0s 2ms/step - loss: 0.4305 - accuracy: 0.8149
Epoch 9/100
160/160 [==============================] - 0s 2ms/step - loss: 0.4324 - accuracy: 0.8125
Epoch 10/100
160/160 [==============================] - 0s 2ms/step - loss: 0.4108 - accura

In [93]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [94]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [95]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[1530   65]
 [ 210  195]]


In [96]:
accuracy_score(y_test, y_pred)

0.8625