In [2]:
import numpy

In [3]:
numpy.__version__

'1.19.5'

In [4]:
numpy.array([10,20,30])

array([10, 20, 30])

In [5]:
import numpy as np

In [22]:
a = np.array([10,20,30])

In [23]:
a

array([10, 20, 30])

In [9]:
a.shape

(3,)

In [10]:
print(type(a))

<class 'numpy.ndarray'>


In [14]:
b = ["Rahul",20,30]

In [15]:
print(type(b))

<class 'list'>


In [16]:
print(b)

['Rahul', 20, 30]


In [18]:
b = np.array([[10,20,30],[40,50,60]])

In [19]:
b

array([[10, 20, 30],
       [40, 50, 60]])

In [20]:
b.shape

(2, 3)

In [24]:
a.shape

(3,)

In [25]:
a.dtype

dtype('int64')

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
range(10)

range(0, 10)

In [28]:
c = range(10000)
%timeit [i**3 for i in c]

100 loops, best of 5: 2.77 ms per loop


In [29]:
c_numpy = np.arange(10000)
%timeit c_numpy**3

The slowest run took 16.47 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 24.4 µs per loop


In [30]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [32]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [33]:
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [34]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [35]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
np.random.random()

0.28242778055237516

In [50]:
50*np.random.random() + 1

6.581141570485215

In [51]:
np.random.random([3,3])

array([[0.77586152, 0.4611469 , 0.09458764],
       [0.97711298, 0.43699974, 0.58170789],
       [0.89229288, 0.27769053, 0.41891182]])

In [53]:
np.linspace(1,50,100)

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [54]:
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [55]:
np.arange(18).reshape(2,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [56]:
np.arange(18).reshape(2,3,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [57]:
a = np.arange(1,10)

In [58]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [60]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [61]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [62]:
np.sum(a)

45

In [64]:
np.mean(a)

5.0

In [65]:
np.median(a)

5.0

In [66]:
np.std(a)

2.581988897471611

In [91]:
a = np.array([[11,20,33],[45,51,60],[17,18,90]])

In [92]:
a

array([[11, 20, 33],
       [45, 51, 60],
       [17, 18, 90]])

In [93]:
np.linalg.det(a)

-23871.00000000002

In [94]:
np.linalg.inv(a)

array([[-0.14704034,  0.05052155,  0.02023376],
       [ 0.12693226, -0.0179716 , -0.03456076],
       [ 0.00238783, -0.00594864,  0.01420133]])

In [84]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [95]:
np.linalg.det(a)

-23871.00000000002